#pragma config(Motor,  port1,           LeftBackWheel, tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           LeftFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           StarGrabber,   tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LiftRight,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           LiftLeft,      tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           RightFrontWheel, tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          RightBackWheel, tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

void goBackwards(float time)
{
	if (time == 0) { // go backwards until sensor is pushed

	}
	else {
		motor[LeftFrontWheel] = -127;
		motor[LeftBackWheel] = 127;
		motor[RightFrontWheel] = 127;
		motor[RightBackWheel] = -127;
		wait1Msec(time * 1000);
		motor[LeftBackWheel] = 0;
		motor[LeftFrontWheel] = 0;
		motor[RightBackWheel] = 0;
		motor[RightFrontWheel] = 0;
	}
}

void goForwards(float time)
{
	motor[LeftFrontWheel] = 127;
	motor[LeftBackWheel] = -127;
	motor[RightFrontWheel] = -127;
	motor[RightBackWheel] = 127;
	wait1Msec(time * 1000);
	motor[LeftBackWheel] = 0;
	motor[LeftFrontWheel] = 0;
	motor[RightBackWheel] = 0;
	motor[RightFrontWheel] = 0;	
}

void turn(float time, char direction) // direction is 'R' for right or 'L' for left
{
	if (direction == '') {
		
	}
	motor[LeftFrontWheel]
}

void LiftStar()
{
	motor[LiftLeft] = 127;
	motor[LiftRight] = -127;
	wait1Msec(1350);
	motor[LiftLeft] = 0;
	motor[LiftRight] = 0;
}

void PutDownLift()
{
	motor[LiftLeft] = -127;
	motor[LiftRight] = 127;
	wait1Msec(740);
	motor[LiftLeft] = 0;
	motor[LiftRight] = 0;
}

task main()
{
	float timeToMid = 2.8;
	motor[StarGrabber] = -50;
	goBackwards(timeToMid);
	LiftStar();
	motor[StarGrabber] = 50;
	wait1Msec(800);
	motor[StarGrabber] = 0;
	wait1Msec(4000);
	goForwards(3);
	PutDownLift();

	while (1 == 1)
	{
		if (vexRT[Ch3] != 1)
		{
			motor[LeftFrontWheel] = vexRT[Ch3];
			motor[LeftBackWheel] = -vexRT[Ch3];
		}
		else
		{
			motor[LeftFrontWheel] = 0;
			motor[LeftBackWheel] = 0;
		}

		if (vexRT[Ch2] != 1) {
			motor[RightBackWheel] = vexRT[Ch2];
			motor[RightFrontWheel] = -vexRT[Ch2];
		}
		else
		{
			motor[RightFrontWheel] = 0;
			motor[RightBackWheel] = 0;
		}

		if (vexRT[Btn5D] == 1) 
		{
			motor[LiftLeft] = -127;
			motor[LiftRight] = 127;
		}
		else if (vexRT[Btn5U] == 1) 
		{
				motor[LiftLeft] = 127;
				motor[LiftRight] = -127;
		}
		else 
		{
			motor[LiftLeft] = 0;
			motor[LiftRight] = 0;
		}

		if (vexRT[Btn6D] == 1) 
		{
			motor[StarGrabber] = -70;
		}
		else if (vexRT[Btn6U] == 1) 
		{
			motor[StarGrabber] = 70;
		}
		else 
		{
			motor[StarGrabber] = 0;
		}

		wait1Msec(30);
		motor[LiftLeft] = 0;
		motor[LiftRight] = 0;
	}

}
